# Generated by Django 4.2.2 on 2023-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
